# Generated by Django 6.0.7 on 2026-07-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='artworks/', verbose_name='Cover image')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'art project',
                'verbose_name_plural': 'art projects',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='entries/')),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Drag to reorder in admin.', verbose_name='Order')),
                ('artproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='with_art.artproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
