# Generated by Django 6.0.7 on 2026-07-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='current/', verbose_name='Cover image')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this project from the CURRENT page without deleting it.', verbose_name='Published')),
            ],
            options={
                'verbose_name': 'current project',
                'verbose_name_plural': 'current projects',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='artproject',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Show this project on the CURRENT page.', verbose_name='Currently on view'),
        ),
        migrations.CreateModel(
            name='CurrentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='current/entries/')),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Drag to reorder in admin.', verbose_name='Order')),
                ('current_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='with_art.currentproject', verbose_name='Current project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
