# Generated by Django 6.0.7 on 2026-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0002_currentproject_artproject_is_current_currententry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artproject',
            options={'ordering': ['order', '-date_added'], 'verbose_name': 'art project', 'verbose_name_plural': 'art projects'},
        ),
        migrations.AlterModelOptions(
            name='currentproject',
            options={'ordering': ['order', '-date_added'], 'verbose_name': 'current project', 'verbose_name_plural': 'current projects'},
        ),
        migrations.AddField(
            model_name='artproject',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Drag to reorder in admin.', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='currentproject',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Drag to reorder in admin.', verbose_name='Order'),
        ),
    ]
