# Generated by Django 4.2.30 on 2026-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0003_alter_artproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproject',
            name='cover_video',
            field=models.FileField(blank=True, null=True, upload_to='covers/video/'),
        ),
    ]
