# Generated by Django 4.2.30 on 2026-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0004_artproject_cover_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='covers/entries/video/'),
        ),
    ]
