# Generated by Django 4.2.30 on 2026-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0005_entry_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='currententry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='covers/entries/video/'),
        ),
        migrations.AddField(
            model_name='currentproject',
            name='cover_video',
            field=models.FileField(blank=True, null=True, upload_to='covers/video/'),
        ),
    ]
