# Generated by Django 4.2.30 on 2026-07-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0006_currententry_video_currentproject_cover_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproject',
            name='cover_image_web',
            field=models.ImageField(blank=True, upload_to='artworks/web/'),
        ),
        migrations.AddField(
            model_name='currententry',
            name='image_web',
            field=models.ImageField(blank=True, upload_to='current/entries/web/'),
        ),
        migrations.AddField(
            model_name='currentproject',
            name='cover_image_web',
            field=models.ImageField(blank=True, upload_to='current/web/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='image_web',
            field=models.ImageField(blank=True, upload_to='entries/web/'),
        ),
        migrations.AlterField(
            model_name='currententry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='currentproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
