# Generated by Django 4.2.30 on 2026-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0007_artproject_cover_image_web_currententry_image_web_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('commission', 'Commission a work'), ('exhibition', 'Exhibition proposal'), ('press', 'Press & media'), ('collaboration', 'Collaboration'), ('purchase', 'Purchase / pricing'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
