# Generated by Django 4.2.30 on 2026-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('with_art', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproject',
            name='cover_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (Cloudinary)'),
        ),
        migrations.AddField(
            model_name='currententry',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (Cloudinary)'),
        ),
        migrations.AddField(
            model_name='currentproject',
            name='cover_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (Cloudinary)'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (Cloudinary)'),
        ),
    ]
